### ISSUE TITLE
Add injury is returning list before end insert operation

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#26]
When I run

```
import requests
response = requests.post(
    'http://localhost:3000/api/v1/imagens-lesoes/{}'.format(9),
    headers=headers,
    json=[
            {
                "nome": "LSIL",
                "detalhes": "",
            },
        ],
)
```

I receive

```
{'status_code': 404, 'mensagem': 'No one injury found'}
```

I suspect that the problem is in `src/executores/imagem_executor/CadastrarLesaoExecutor.js` at

```
        for (let i = 0; i < total; i++) {
            await ImagemRepositorio.cadastrarLesao(req.body[i]);
        }

        return await ListarLesoes.Executar(req);
```

**Comment by bernardofagner** [comment]
Olá!

Provavelmente é algum erro na sua requisição, vc tentou fazer essa chamada via Postman? Se vc está tentando obter algum registro de lesão, o verbo a ser usado é GET e não há body na requisição, se quer cadastrar alguma nova lesão, o verbo é POST e vc precisa se atentar à sintaxe do seu json. O parâmetro do bory em uma chamada POST é um array de pesões. Atente para o formato do seu Json, eu estou vendo 2 virgulas ali que não deveriam estar ali. Dê uam olhada no código em Angular na classe ImagemService, no método de cadastrar uma nova lesão e dê uma olhada na sintaxe usada lá. Pode te ajudar


De: Raniere Silva [mailto:notifications@github.com]
Enviada em: quarta-feira, 25 de março de 2020 21:26
Para: CRICDatabase/searchable-image-database-nodejs
Cc: bernardofagner; Assign
Assunto: [CRICDatabase/searchable-image-database-nodejs] Add injury is returning list before end insert operation (#26)


When I run

import requests

response = requests.post(

    'http://localhost:3000/api/v1/imagens-lesoes/{}'.format(9),

    headers=headers,

    json=[

            {

                "nome": "LSIL",

                "detalhes": "",

            },

        ],

)

I receive

{'status_code': 404, 'mensagem': 'No one injury found'}

I suspect that the problem is in src/executores/imagem_executor/CadastrarLesaoExecutor.js at

        for (let i = 0; i < total; i++) {

            await ImagemRepositorio.cadastrarLesao(req.body[i]);

        }



        return await ListarLesoes.Executar(req);

**Comment by rgaiacs** [comment]
This is happening because the `id` 1 is being used as reserved and removed when returning the JSON.

**Comment by rgaiacs** [comment]
Close by https://github.com/CRICDatabase/searchable-image-database-nodejs/pull/138
